[package]
name = "godcoin"
version = "0.0.1"
authors = ["Samuel Grenier <samrg472@gmail.com>"]

[lib]
name = "godcoin"
path = "src/godcoin/lib.rs"

[dependencies]
bs58 = "0.2.1"
bytes = "0.4.9"
crc32c = "0.4.0"
crossbeam-channel = "0.2.5"
dirs = "1.0.3"
env_logger = "0.5.12"
futures = "0.1.24"
log = "0.4.4"
num-bigint = "0.2.0"
num-traits = "0.2.5"
parking_lot = "0.6.4"
rand = "0.5.5"
rocksdb = "0.10.1"
sodiumoxide = { version = "0.1.0", default-features = false, features = ["std"] }
tokio = "0.1.7"
tokio-codec = "0.1.0"
