[package]
name = "godcoin"
version = "0.0.1"
authors = ["Samuel Grenier <samrg472@gmail.com>"]
edition = "2018"

[lib]
name = "godcoin"
path = "src/godcoin/lib.rs"

[dependencies]
bs58 = "0.2.2"
bytes = "0.4.12"
crc32c = "0.4.0"
crossbeam-channel = "0.3.8"
futures = "0.1.25"
log = "0.4.6"
num-bigint = "0.2.2"
num-traits = "0.2.6"
parking_lot = "0.7.1"
rand = "0.6.5"
rocksdb = "0.11.0"
sodiumoxide = { version = "0.2.1", default-features = false, features = ["std"] }
tokio = "0.1.16"
tokio-codec = "0.1.1"
