[package]
name = "godcoin-server"
version = "0.0.1"
authors = ["Samuel Grenier <samrg472@gmail.com>"]
edition = "2018"

[dependencies]
actix = "0.8.1"
bytes = "0.4.12"
dirs = "1.0.5"
env_logger = "0.6.1"
godcoin = { path = "../godcoin" }
log = "0.4.6"

[dependencies.actix-web]
version = "1.0.0-beta.1"
default-features = false

[lib]
name = "server"
path = "src/server/lib.rs"

[[bin]]
name = "godcoin-server"
path = "src/bin/server/main.rs"
test = false
doc = false
